title: Stack Problems
description: My Personal Stack Problems
author: Chao Peng
github: https://github.com/chaopengio
about: I am a architech of big data. Mainly focus on hadoop, hbase, etc.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "www.linkedin.com/in/chao-peng"
    - icon: fa-stack-exchange
      link: "#"

share:
  twitter_username: chaopeng
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/chaopengio
    - text: XML Feed
      url: /feed.xml

url: "https://chaopengio.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
